config/routes.rb
Rails.application.routes.draw do

  resources :ips

  get 'inform/new'

  root 'home#index'
  match '/editor', to: 'home#editor', via: 'get'
  devise_for :admin_users, controllers: { sessions: "sessions" }

  resources :admin_companies
  resources :companies, :except => [:new, :destroy, :create]
  resources :admins, controller: 'admin_users'
  resources :informs
  resources :plugins, :only => [:index, :create, :destroy]
  resources :logs, :only => [:index]
  get '/admin_infos/:id', to: 'admin_infos#show'
  get '/admin_infos/:id/edit', to: 'admin_infos#edit'
  get '/admin_infos/:id/password', to: 'admin_infos#password'
  patch 'admin_infos/:id/edit', to: 'admin_infos#update'
  patch '/admin_infos/:id/password', to: 'admin_infos#update_password'

  resources :products  do
    post 'destroy_ids', on: :collection
  end

  resources :informs  do
    post 'destroy_ids', on: :collection
  end

  resources :push_messages, :except => [:edit]
  resources :pads
  
  mount API::Root => '/'

end

app/models/pad.rb
class Pad < ActiveRecord::Base
	has_one :pad_user
	has_one :baidu_push
	belongs_to :company
	validates :Mac_address, :presence => { :message => "不能为空字符" }, uniqueness: { case_sensitive: false }, 
	format: { with: /([a-zA-Z]|\d){2}:([a-zA-Z]|\d){2}:([a-zA-Z]|\d){2}:([a-zA-Z]|\d){2}:([a-zA-Z]|\d){2}:([a-zA-Z]|\d){2}/, message: '格式为XX:XX:XX:XX:XX:XX'}

	attr_accessor :pad_user_name

	def save
		if !super
			return false
		end
		PadUser.create(:name => self.pad_user_name, :pad_id => self.id)
	end

	def update(pad_params)
		if !super(pad_params)
			return false
		end
		user = self.pad_user
		user.update(:name => self.pad_user_name)
	end
end

app/controllers/pads_controller.rb
class PadsController < ApplicationController
  before_action :set_pad, only: [:show, :edit, :update, :destroy]

  # GET /pads
  # GET /pads.json
  def index
    @pads = current_admin_user.company.pads
  end

  # GET /pads/1
  # GET /pads/1.json
  def show
  end

  # GET /pads/new
  def new
    @pad = Pad.new
  end

  # GET /pads/1/edit
  def edit
  end

  # POST /pads
  # POST /pads.json
  def create
    @pad = Pad.new(pad_params)
    @pad.company_id = current_admin_user.company.id

    respond_to do |format|
      if @pad.save
        @log = Log.create(:admin_user_id => current_admin_user.id, :company_id => current_admin_user.company.id, :event => "新建平板", :description => "#{current_admin_user.username}新建了MAC地址为#{@pad.Mac_address}的平板")
        format.html { redirect_to @pad, notice: '新建成功！' }
        format.json { render :show, status: :created, location: @pad }
      else
        format.html { render :new}
        format.json { render json: @pad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pads/1
  # PATCH/PUT /pads/1.json
  def update
      @tmp = Pad.new(:Mac_address => @pad.Mac_address)
    respond_to do |format|
      if @pad.update(pad_params)
       @log = Log.create(:admin_user_id => current_admin_user.id, :company_id => current_admin_user.company.id, :event => "编辑平板", :description => "#{current_admin_user.username}将MAC地址#{@tmp.Mac_address}更新为#{@pad.Mac_address}")
       format.html { redirect_to @pad, notice: '编辑成功！' }
       format.json { render :show, status: :ok, location: @pad }
     else
      format.html { render :edit }
      format.json { render json: @pad.errors, status: :unprocessable_entity }
    end
  end
end

  # DELETE /pads/1
  # DELETE /pads/1.json
  def destroy
    @log = Log.create(:admin_user_id => current_admin_user.id, :company_id => current_admin_user.company.id, :event => "删除平板", :description => "#{current_admin_user.username}删除了MAC地址为#{@pad.Mac_address}的平板")
    @pad.destroy
    respond_to do |format|
      format.html { redirect_to pads_url, notice: '删除成功！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pad
      @pad = Pad.find(params[:id])
      if  @pad.nil? || (@pad.company_id != current_admin_user.company.id )
        redirect_to pads_path  
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pad_params
      params.require(:pad).permit(:Mac_address, :company_id, :pad_user_name)
    end

  end

app/helpers/pads_helper.rb
module PadsHelper
end

app/views/pads/_form.html.erb
<%= form_for(@pad) do |f| %>

<% if @pad.errors.any? %>
<div class="alert alert-block alert-error">
	<a class="close" data-dismiss="alert" href="#">×</a>
	<p><strong>有 <%= @pad.errors.count %> 处问题导致无法提交:</strong></p>
	<ul>
		<% @pad.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">

 <% if@pad.errors.any?%>
            <label class="string required control-label error">MAC地址:</label>
            <% else %>
            <label>MAC地址:</label>
            <% end %>
	<br>
	<%= f.text_field :Mac_address, class:(@pad.errors.any?) ? "form-control error" : "form-control" %>
	<br>


	 <% if@pad.errors.any?%>
            <label class="string required control-label error">用户名:</label>
            <% else %>
            <label>用户名:</label>
            <% end %>
	<br>
	<%= f.text_field :pad_user_name, class:(@pad.errors.any?) ? "form-control error" : "form-control", value: (@pad.pad_user.nil?)? "" : @pad.pad_user.name  %>
</div>
	<%= f.submit '提交' ,class:"btn btn-outline btn-primary", role:"button"%>
<% end %>

app/views/pads/edit.html.erb
  <br>
  <div class="panel panel-default">
   <div class="panel-heading">编辑平板</div>
      <div class="panel-body">
        <div class="table-responsive">
    <%= render 'form' %>
  <%= link_to '查看', @pad, class:"btn btn-outline btn-primary" %> 
  <%= link_to '返回', pads_path, class:"btn btn-outline btn-primary"%>

app/views/pads/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        平板管理
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
       <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th class="textstyle">MAC地址</th>
              <th class="textstyle">用户</th>
              <th class="textstyle">操作</th>
            </tr>
          </thead>

          <tbody>
            <% @pads.each do |pad| %>
            <tr>
              <td class="textstyle"><%= pad.Mac_address %></td>
              <td class="textstyle"><%= pad.pad_user.name%></td>
              <td class="textstyle"><%= link_to '查看', pad %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to '编辑', edit_pad_path(pad) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to '删除', pad, method: :delete, data: { confirm: '您确定要删除?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>

<%= link_to '新建平板', new_pad_path, class:"btn btn-outline btn-primary", role:"button"%>

      </div>
      <!-- /.table-responsive -->
    </div>

    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->

</div>

</div>

app/views/pads/new.html.erb
<% provide(:title, '新建')  %>
<br>
<div class="panel panel-default">
   <div class="panel-heading">新建平板</div>
      <div class="panel-body">
        <div class="table-responsive">
    <%= render 'form' %>
    <%= link_to '返回', pads_path, class:"btn btn-outline btn-primary" %>
    </div>
  </div>
</div>
</div>

app/views/pads/show.html.erb
<br>
<% if !notice.nil?  %>
<p id="notice" class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><%= notice %></p>
<% end %>
<!-- /.row -->
<div class="row">
	<div class="col-lg-4">
		<div class="well">
			<h4>MAC地址</h4>
			<p><%= @pad.Mac_address%></p>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="well">
			<h4>用户</h4>
			<p><%= @pad.pad_user.name%></p>
		</div>
	</div>
</div>
<!-- /.row -->                
<%= link_to '编辑', edit_pad_path(@pad), class:"btn btn-outline btn-primary" %> 
<%= link_to '返回', pads_path, class:"btn btn-outline btn-primary" %>