config/routes.rb
Rails.application.routes.draw do

  resources :ips

  get 'inform/new'

  root 'home#index'
  match '/editor', to: 'home#editor', via: 'get'
  devise_for :admin_users, controllers: { sessions: "sessions" }

  resources :admin_companies
  resources :companies, :except => [:new, :destroy, :create]
  resources :admins, controller: 'admin_users'
  resources :informs
  resources :plugins, :only => [:index, :create, :destroy]
  resources :logs, :only => [:index]
  get '/admin_infos/:id', to: 'admin_infos#show'
  get '/admin_infos/:id/edit', to: 'admin_infos#edit'
  get '/admin_infos/:id/password', to: 'admin_infos#password'
  patch 'admin_infos/:id/edit', to: 'admin_infos#update'
  patch '/admin_infos/:id/password', to: 'admin_infos#update_password'

  resources :products  do
    post 'destroy_ids', on: :collection
  end

  resources :informs  do
    post 'destroy_ids', on: :collection
  end

  resources :push_messages, :except => [:edit]
  resources :pads
  
  mount API::Root => '/'

end

app/controllers/admin_companies_controller.rb
class AdminCompaniesController < ApplicationController
  before_action :set_admin_company, only: [:show, :edit, :update, :destroy]
  before_filter :check_role
  # GET /admin_companies
  # GET /admin_companies.json
  def index
    @admin_companies = Company.all
  end

  # GET /admin_companies/1
  # GET /admin_companies/1.json
  def show
  end

  # GET /admin_companies/new
  def new
    @admin_company = Company.new
    @admin = AdminUser.new
  end

  # GET /admin_companies/1/edit
  def edit
  end

  # POST /admin_companies
  # POST /admin_companies.json
  def create
    @admin_company = Company.new(admin_company_params)
    @admin = AdminUser.new(:username => @admin_company.username, :email => @admin_company.email, :password => @admin_company.password, :password_confirmation => @admin_company.password_confirmation)
    respond_to do |format|
      if @admin_company.save && @admin.save
        @admin.company_id = @admin_company.id
        @admin.save
        @admin.add_role :admin
        format.html { redirect_to admin_company_path(@admin_company), notice: '新建成功！' }
        format.json { render :show, status: :created, location: @admin_company }
      else
        format.html { render :new }
        format.json { render json: @admin_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_companies/1
  # PATCH/PUT /admin_companies/1.json
  def update
    respond_to do |format|
      if @admin_company.update(admin_company_params)
        format.html { redirect_to admin_company_path(@admin_company), notice: '编辑成功！' }
        format.json { render :show, status: :ok, location: @admin_company }
      else
        format.html { render :edit }
        format.json { render json: @admin_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_companies/1
  # DELETE /admin_companies/1.json
  def destroy
    @admin_company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: '删除成功！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_company
      @admin_company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_company_params
      params.require(:company).permit(:company_name, :company_address, :company_tel, :username, :email, :password, :password_confirmation)
    end

    def check_role
      if !current_admin_user.has_role? :root_admin
        redirect_to root_path
      end
    end
  end

app/helpers/admin_companies_helper.rb
module AdminCompaniesHelper
end

app/views/admin_companies/edit.html.erb
<br>
<div class="panel panel-default">
  <div class="panel-heading">编辑公司</div>
  <div class="panel-body">
    <div class="table-responsive">
      <%= form_for(@admin_company, url: admin_company_path(@admin_company)) do |f| %>
      <% if @admin_company.errors.any? %>
      <div class="alert alert-block alert-error">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <p><strong>有 <%= @admin_company.errors.count %> 处问题导致无法提交:</strong></p>
        <ul>
          <% @admin_company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="field">

       <% if@admin_company.errors.any?%>
       <label class="string required control-label error">公司名字:</label>
       <% else %>
       <label>公司名字:</label>
       <% end %>
       <%= f.text_field :company_name, class:(@admin_company.errors.any?) ? "form-control error" : "form-control",value: (@admin_company.company_name.nil?)? "" : @admin_company.company_name %>
     </div>
     <div class="field">
       <% if@admin_company.errors.any?%>
       <label class="string required control-label error">公司地址:</label>
       <% else %>
       <label>公司地址:</label>
       <% end %>
       <%= f.text_field :company_address, class:(@admin_company.errors.any?) ? "form-control error" : "form-control", value: (@admin_company.company_address.nil?)? "" : @admin_company.company_address %>
     </div>
     <div class="field">

      <% if@admin_company.errors.any?%>
      <label class="string required control-label error">公司电话:</label>
      <% else %>
      <label>公司电话:</label>
      <% end %>
      <%= f.text_field :company_tel, class:(@admin_company.errors.any?) ? "form-control error" : "form-control", value: (@admin_company.company_tel.nil?)? "" : @admin_company.company_tel%>
    </div>
    <div class="actions">
     <%= f.submit "提交", class:"btn btn-outline btn-primary "%>
     <%= link_to '返回', admin_companies_path, class:"btn btn-outline btn-primary" %>
   </div>
   <% end %>

app/views/admin_companies/index.html.erb
<!-- /.row -->
<br>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        公司管理
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
       <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th class="textstyle">公司名称</th>
              <th class="textstyle">公司地址</th>
              <th class="textstyle">公司电话</th>
              <th class="textstyle">操作</th>
            </tr>
          </thead>

          <tbody>
            <% @admin_companies.each do |company| %>
            <tr>
              <td class="textstyle"><%= company.company_name %></td>
              <td class="textstyle"><%= company.company_address%></td>
              <td class="textstyle"><%= company.company_tel%></td>
              <td class="textstyle"><%= link_to '查看', admin_company_path(company) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to '编辑', edit_admin_company_path(company) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to '删除', admin_company_path(company), method: :delete, data: { confirm: '您确定要删除?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>

          <%= link_to '新建公司', new_admin_company_path, class:"btn btn-outline btn-primary", role:"button"%>

        </div>
        <!-- /.table-responsive -->
      </div>

      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->

  </div>

</div>

app/views/admin_companies/new.html.erb
<br>
<div class="panel panel-default">
  <div class="panel-heading">新建公司</div>
  <div class="panel-body">
    <div class="table-responsive">
      <%= form_for(@admin_company, url: admin_companies_path, method: "post") do |f| %>
      <% if @admin_company.errors.any? %>
      <div class="alert alert-block alert-error">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <p><strong>有 <%= @admin_company.errors.count %> 处问题导致无法提交:</strong></p>
        <ul>
          <% @admin_company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <% if @admin.errors.any? %>
      <div class="alert alert-block alert-error">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <p><strong>有 <%= @admin.errors.count %> 处问题导致无法提交:</strong></p>
        <ul>
          <% @admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="field">

       <% if@admin_company.errors.any?%>
       <label class="string required control-label error">公司名字:</label>
       <% else %>
       <label>公司名字</label>
       <% end %>
       <%= f.text_field :company_name, class:(@admin_company.errors.any?) ? "form-control error" : "form-control",value: (@admin_company.company_name.nil?)? "" : @admin_company.company_name %>
     </div>
     <div class="field">
       <% if@admin_company.errors.any?%>
       <label class="string required control-label error">公司地址:</label>
       <% else %>
       <label>公司地址</label>
       <% end %>
       <%= f.text_field :company_address, class:(@admin_company.errors.any?) ? "form-control error" : "form-control", value: (@admin_company.company_address.nil?)? "" : @admin_company.company_address %>
     </div>
     <div class="field">

      <% if@admin_company.errors.any?%>
      <label class="string required control-label error">公司电话:</label>
      <% else %>
      <label>公司电话</label>
      <% end %>
      <%= f.text_field :company_tel, class:(@admin_company.errors.any?) ? "form-control error" : "form-control", value: (@admin_company.company_tel.nil?)? "" : @admin_company.company_tel%>
    </div>
    <div class="field">

      <% if@admin_company.errors.any?%>
      <label class="string required control-label error">用户名</label>
      <% else %>
      <label>用户名</label>
      <% end %>
      <%= f.text_field :username, class:(@admin_company.errors.any?) ? "form-control error" : "form-control", value: (@admin_company.username.nil?)? "" : @admin_company.username%>
    </div>
    <div class="field">

      <% if@admin_company.errors.any?%>
      <label class="string required control-label error">邮箱</label>
      <% else %>
      <label>邮箱</label>
      <% end %>
      <%= f.text_field :email, class:(@admin_company.errors.any?) ? "form-control error" : "form-control", value: (@admin_company.email.nil?)? "" : @admin_company.email%>
    </div>
    <div class="field">

      <% if@admin_company.errors.any?%>
      <label class="string required control-label error">密码</label>
      <% else %>
      <label>密码</label>
      <% end %>
      <%= f.text_field :password, class:(@admin_company.errors.any?) ? "form-control error" : "form-control", value: (@admin_company.password.nil?)? "" : @admin_company.password%>
    </div>
    <div class="field">

      <% if@admin_company.errors.any?%>
      <label class="string required control-label error">确认密码</label>
      <% else %>
      <label>确认密码</label>
      <% end %>
      <%= f.text_field :password_confirmation, class:(@admin_company.errors.any?) ? "form-control error" : "form-control", value: (@admin_company.password_confirmation.nil?)? "" : @admin_company.password_confirmation%>
    </div>
    <div class="actions">
     <%= f.submit "提交", class:"btn btn-outline btn-primary "%>
     <%= link_to '返回', admin_companies_path, class:"btn btn-outline btn-primary" %>
   </div>
   <% end %>

app/views/admin_companies/show.html.erb
<br>
<% if !notice.nil?  %>
<p id="notice" class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><%= notice %></p>
<% end %>
<!-- /.row -->
<div class="row">
	<div class="col-lg-4">
		<div class="well">
			<h4>公司名称</h4>
			<p><%= @admin_company.company_name%></p>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="well">
			<h4>公司地址</h4>
			<p><%= @admin_company.company_address%></p>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="well">
			<h4>公司电话</h4>
			<p><%= @admin_company.company_tel%></p>
		</div>
	</div>
</div>
<!-- /.row -->                
<%= link_to '编辑', edit_admin_company_path(@admin_company), class:"btn btn-outline btn-primary" %> 
<%= link_to '返回', admin_companies_path, class:"btn btn-outline btn-primary" %>