config/routes.rb
Rails.application.routes.draw do

  resources :ips

  get 'inform/new'

  root 'home#index'
  match '/editor', to: 'home#editor', via: 'get'
  devise_for :admin_users, controllers: { sessions: "sessions" }

  resources :admin_companies
  resources :companies, :except => [:new, :destroy, :create]
  resources :admins, controller: 'admin_users'
  resources :informs
  resources :plugins, :only => [:index, :create, :destroy]
  resources :logs, :only => [:index]
  get '/admin_infos/:id', to: 'admin_infos#show'
  get '/admin_infos/:id/edit', to: 'admin_infos#edit'
  get '/admin_infos/:id/password', to: 'admin_infos#password'
  patch 'admin_infos/:id/edit', to: 'admin_infos#update'
  patch '/admin_infos/:id/password', to: 'admin_infos#update_password'

  resources :products  do
    post 'destroy_ids', on: :collection
  end

  resources :informs  do
    post 'destroy_ids', on: :collection
  end

  resources :push_messages, :except => [:edit]
  resources :pads
  
  mount API::Root => '/'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login

  belongs_to :company

  validates :username, :presence => { :message => "不能为空字符" }, uniqueness: { case_sensitive: false }

 
  def login=(login)
  	@login = login
  end

  def login
  	@login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
  	conditions = warden_conditions.dup
  	if login = conditions.delete(:login)
  		where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  	else
  		where(conditions).first
  	end
  end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
	before_action :set_admin_user, only: [:show, :edit, :update, :destroy]
  before_filter :check_role
  # GET /admin_users
  # GET /admin_users.json
  def index
  	@admins =  current_admin_user.company.admin_users
  end

  # GET /admin_users/1
  # GET /admin_users/1.json
  def show
  end

  # GET /admin_users/new
  def new
    @admin = AdminUser.new
  end

  # GET /admin_users/1/edit
  def edit
  end

  # POST /admin_users
  # POST /admin_users.json
  def create
    @admin = AdminUser.new(admin_params)
    @admin.company_id = current_admin_user.company.id
    respond_to do |format|
      if @admin.save
        @log = Log.create(:admin_user_id => current_admin_user.id, :company_id => current_admin_user.company.id, :event => "新建管理员", :description => "#{current_admin_user.username}新建了名字为#{@admin.username}的管理员")
        format.html { redirect_to admin_path(@admin), notice: '新建成功！' }
        format.json { render :show, status: :created, location: @admin }
      else
       format.html { render :new}
       format.json { render json: @admin.errors, status: :unprocessable_entity }
     end
   end
 end

  # PATCH/PUT /admin_users/1
  # PATCH/PUT /admin_users/1.json
  def update
    @tmp = AdminUser.new(:username => @admin.username)
    respond_to do |format|
      if  @admin.update(admin_params) && current_admin_user.valid_password?(params[:admin_user][:current_password])
        @log = Log.create(:admin_user_id => current_admin_user.id, :company_id => current_admin_user.company.id, :event => "编辑管理员", :description => "#{current_admin_user.username}将名字#{@tmp.username}更新为#{@admin.username}")
       format.html { redirect_to admin_path(@admin), notice: '编辑成功！' }
       format.json { render :show, status: :ok, location: @admin }
     else
       format.html { render :edit }
       format.json { render json: @admin.errors, status: :unprocessable_entity }
     end
   end
 end

  # DELETE /admin_users/1
  # DELETE /admin_users/1.json
  def destroy
    if !@admin.has_role? :admin	
      @log = Log.create(:admin_user_id => current_admin_user.id, :company_id => current_admin_user.company.id, :event => "删除管理员", :description => "#{current_admin_user.username}删除了名字为#{@admin.username}的管理员")
      @admin.destroy
      respond_to do |format|
        format.html { redirect_to admins_url, notice: '删除成功！' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to admins_url, notice: '你不能删除根管理员！' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
    	@admin = AdminUser.find(params[:id])
    	if @admin.nil? || ( @admin.company_id != current_admin_user.company.id )
    		redirect_to admins_path  
    	end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
    	params.require(:admin_user).permit(:username, :email, :password, :password_confirmation, :company_id)
    end

    def root_url
      return root_path
    end

    def check_role
      if !current_admin_user.has_role? :admin
        redirect_to root_path
      end
    end
  end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/edit.html.erb
  <br>
  <div class="panel panel-default">
  	<div class="panel-heading">修改密码</div>
  	<div class="panel-body">
  		<div class="table-responsive">
  			<%= form_for(@admin, url: admin_path(@admin)) do |f| %>
        <%if params[:admin_user] %>
        <% if !current_admin_user.valid_password?(params[:admin_user][:current_password]) %>
        <div class="alert alert-block alert-error">
          <a class="close" data-dismiss="alert" href="#">×</a>
          <p><strong>有 1 处问题导致无法提交:</strong></p>
          <ul>
            <li>管理员密码 错误</li>
          </ul>
        </div>
        <% elsif @admin.errors.any? %>
        <div class="alert alert-block alert-error">
          <a class="close" data-dismiss="alert" href="#">×</a>
          <p><strong>有 <%= @admin.errors.count %> 处问题导致无法提交:</strong></p>
          <ul>
           <% @admin.errors.full_messages.each do |message| %>
           <li><%= message %></li>
           <% end %>
         </ul>
       </div>
       <% end %>
       <% end %> 
       <div class="field">
        <% if @admin.errors.any? %>
        <label class="string required control-label error" >管理员密码</label>
        <br>
        <input class="form-control error" id="admin_user_current_password" name="admin_user[current_password]" type="password" >
        <br>
        <label class="string required control-label error" >新密码</label>
        <br>
        <%= f.password_field :password, class:"form-control error" %>
        <br>
        <label class="string required control-label error" >确认密码</label>
        <br>
        <%= f.password_field :password_confirmation, class:"form-control error" %>
        <% else %>
        <label class="string required control-label" >管理员密码</label>
        <br>
        <input class="form-control" id="admin_user_current_password" name="admin_user[current_password]" type="password" >
        <br>
        <label class="string required control-label" >新密码</label>
        <br>
        <%= f.password_field :password, class:"form-control" %>
        <br>
        <label class="string required control-label" >确认密码</label>
        <br>
        <%= f.password_field :password_confirmation, class:"form-control" %>
        <% end %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit '提交' ,class:"btn btn-outline btn-primary", role:"button"%>
        <%= link_to '查看', admin_path(@admin), class:"btn btn-outline btn-primary" %> 
        <%= link_to '返回', admins_path, class:"btn btn-outline btn-primary"%>
      </div>
      <% end %>

app/views/admin_users/index.html.erb
<!-- /.row -->
<br>
<% if !notice.nil?  %>
<p id="notice" class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><%= notice %></p>
<% end %>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        管理员管理
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
       <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th class="textstyle">用户名</th>
              <th class="textstyle">邮箱</th>
              <th class="textstyle">操作</th>
            </tr>
          </thead>

          <tbody>
            <% @admins.each do |admin_user| %>
            <tr>
              <td class="textstyle"><%= admin_user.username %></td>
              <td class="textstyle"><%= admin_user.email%></td>
              <td class="textstyle">
                <%= link_to '查看', admin_path(admin_user) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to '修改密码', edit_admin_path(admin_user) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to '删除', admin_path(admin_user), method: :delete, data: { confirm: '您确定要删除?' } %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>

      </table>

    </div>
    <!-- /.table-responsive -->
  </div>

  <!-- /.panel-body -->
</div>
<!-- /.panel -->

</div>

</div>

<%= link_to '新建管理员', new_admin_path, class:"btn btn-outline btn-primary", role:"button"%>

app/views/admin_users/new.html.erb
<% provide(:title, '新建')  %>
<br>
<div class="panel panel-default">
	<div class="panel-heading">新建管理员</div>
	<div class="panel-body">
		<div class="table-responsive">
			<%= form_for(@admin, url: admins_path ) do |f| %>
			<% if @admin.errors.any? %>
			<div class="alert alert-block alert-error">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<p><strong>有 <%= @admin.errors.count %> 处问题导致无法提交:</strong></p>
				<ul>
					<% @admin.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
			<div class="field">
				<% if @admin.errors.any? %>
				<label class="string required control-label error" >用户名</label>
				<br>
				<%= f.text_field :username, class:"form-control error"  %>
				<br>
				<label class="string required control-label error" >邮箱</label>
				<br>
				<%= f.text_field :email, class:"form-control error" %>
				<br>
				<label class="string required control-label error" >密码</label>
				<br>
				<%= f.password_field :password, class:"form-control error" %>
				<br>
				<label class="string required control-label error" >确认密码</label>
				<br>
				<%= f.password_field :password_confirmation, class:"form-control error" %>
				<% else %>
				<label class="string required control-label" >用户名</label>
				<br>
				<%= f.text_field :username, class:"form-control"  %>
				<br>
				<label class="string required control-label" >邮箱</label>
				<br>
				<%= f.text_field :email, class:"form-control" %>
				<br>
				<label class="string required control-label" >密码</label>
				<br>
				<%= f.password_field :password, class:"form-control" %>
				<br>
				<label class="string required control-label" >确认密码</label>
				<br>
				<%= f.password_field :password_confirmation, class:"form-control" %>
				<% end %>
			</div>
			<br>
			<div class="actions">
				<%= f.submit '提交' ,class:"btn btn-outline btn-primary", role:"button"%>
				<%= link_to '返回', admins_path, class:"btn btn-outline btn-primary" %>
			</div>
			<% end %>
		</div>
	</div>
</div>
</div>

app/views/admin_users/show.html.erb
<br>
<% if !notice.nil?  %>
<p id="notice" class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><%= notice %></p>
<% end %>
<!-- /.row -->
<div class="row">
	<div class="col-lg-4">
		<div class="well">
			<h4>用户名</h4>
			<p><%= @admin.username%></p>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="well">
			<h4>邮箱</h4>
			<p><%= @admin.email%></p>
		</div>
	</div>
</div>
<!-- /.row -->                
<%= link_to '编辑', edit_admin_path(@admin), class:"btn btn-outline btn-primary" %> 
<%= link_to '返回', admins_path, class:"btn btn-outline btn-primary" %>