config/routes.rb
Rails.application.routes.draw do

  resources :ips

  get 'inform/new'

  root 'home#index'
  match '/editor', to: 'home#editor', via: 'get'
  devise_for :admin_users, controllers: { sessions: "sessions" }

  resources :admin_companies
  resources :companies, :except => [:new, :destroy, :create]
  resources :admins, controller: 'admin_users'
  resources :informs
  resources :plugins, :only => [:index, :create, :destroy]
  resources :logs, :only => [:index]
  get '/admin_infos/:id', to: 'admin_infos#show'
  get '/admin_infos/:id/edit', to: 'admin_infos#edit'
  get '/admin_infos/:id/password', to: 'admin_infos#password'
  patch 'admin_infos/:id/edit', to: 'admin_infos#update'
  patch '/admin_infos/:id/password', to: 'admin_infos#update_password'

  resources :products  do
    post 'destroy_ids', on: :collection
  end

  resources :informs  do
    post 'destroy_ids', on: :collection
  end

  resources :push_messages, :except => [:edit]
  resources :pads
  
  mount API::Root => '/'

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :company
	validates_confirmation_of :product_name
	validates_presence_of :product_name
	validates_confirmation_of :brief
	validates_presence_of :brief
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:search].nil?
      @products = current_admin_user.company.products.page(params[:page])
    else
      @products = current_admin_user.company.products.where('product_name LIKE ?',"%#{params[:search]}%").page(params[:page])
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end


  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.company_id = current_admin_user.company_id
    respond_to do |format|
      if @product.save
       @log = Log.create(:admin_user_id => current_admin_user.id, :company_id => current_admin_user.company.id, :event => "新建商品", :description => "#{current_admin_user.username}新建了名字为#{@product.product_name}的商品")
       format.html { redirect_to @product, notice: '成功添加商品信息！' }
       format.json { render :show, status: :created, location: @product }
     else
      format.html { render :new }
      format.json { render json: @product.errors, status: :unprocessable_entity }
    end
  end
end
  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json

  def update
    @tmp = Product.new(:product_name => @product.product_name)
    respond_to do |format|
      if @product.update(product_params)
        @log = Log.create(:admin_user_id => current_admin_user.id, :company_id => current_admin_user.company.id, :event => "编辑商品", :description => "#{current_admin_user.username}将名字#{@tmp.product_name}更新为#{@product.product_name}")
        format.html { redirect_to  @product, notice: '成功修改商品信息！' }
        format.json { render json: @product, :status => "ok"}
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @log = Log.create(:admin_user_id => current_admin_user.id, :company_id => current_admin_user.company.id, :event => "删除商品", :description => "#{current_admin_user.username}删除了名字为#{@product.product_name}的商品")
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: '成功删除产品信息！' }
      format.json { head :no_content }
    end
  end 

  # POST /products/destroy_ids
  # POST /products/destroy_ids.json
  def destroy_ids
    params[:ids].split(",").each do | id |
      product = Product.find_by_id(id)
      if !product.nil? && (product.company_id == current_admin_user.company_id)
        product.destroy
      end
    end

    respond_to do |format|
      format.html { redirect_to products_url, notice: '成功删除产品信息！' }
      format.json { render json: params, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      if @product.nil? || ( @product.company_id != current_admin_user.company_id )
        redirect_to informs_path  
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_id, :product_name, :brief, :context, :created_at, :updated_at)
    end
  end

  def self.search(search, page)
    paginate :per_page => 5, :page => page,
    :conditions => ['name like ?', "%#{search}%"], :order => 'name'
  end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% provide(:title, '产品展示')  %>

<%= content_for :header_js do %>
<%= javascript_include_tag 'plugins/ueditor/ueditor.config', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'plugins/ueditor/ueditor.all.min', 'data-turbolinks-track' => true %>
<% end %>
<%= content_for :footer_js do %>
<%= javascript_include_tag 'plugins/ueditor/ueditor','data-turbolinks-track' => true %>
<% end %>


  <%= form_for(@product) do |f| %>
      <% if @product.errors.any? %>
            <div class="alert alert-block alert-error" id="error-div" style="display:none">
            <a class="close" data-dismiss="alert" href="#">×</a>
            <p><strong>有处问题导致无法提交:</strong></p>
            <ul>
            </ul>
            <% end %>
  </div>

<div class="field" id="name">
      <label>产品名字</label>
      <%= f.text_field :product_name, class:"form-control" %>
</div>

<div class="field" id="pro-brief">
     <label>摘要</label>
      <%= f.text_field :brief,  class:"form-control" %>
</div>

<div class="field">
     <label>产品描述:</label>
     <script id="editor" type="text/plain" style="width:100%; height:500px;"></script>
    </div>  
<% end %>

<button class="btn btn-outline btn-primary", id="edit_button">提交</button>




<script type="text/javascript">
  var ue = UE.getEditor('editor');

  ue.ready(function() {
   html = unescape("<%= @product.context%>");  
   $('#ueditor_0').contents().find('body').append(html);
 });
</script>


<script type="text/javascript">
  function form_send (url, request_type) {
    $("#edit_button").click(function () {
       if ($("#product_product_name").val().length !=0 && $("#product_brief").val() !=0){
        console.log("ddd");
       $.ajax({
        url: url,
        dataType: "json",
        type: request_type,
        data: {
          "product[product_name]" :$("#product_product_name").val(), 
          "product[brief]" : $("#product_brief").val(), 
          "product[context]" : escape(UE.getEditor('editor').getAllHtml()),
          "authenticity_token" : $("input[name='authenticity_token']").attr("value"),
          "utf8": $("input[name='utf8']").attr("value")
        },
        })

      .done(function( data) {
        console.log(data);
      })
      .fail(function ( jqXHR, textStatus, errorThrown ) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      })
      .always(function( data ) {
       location.href = url
     })
    }else{
       $('#error-div').css("display","none");
       $('#error-div').children().filter('li').remove();
       $("#error-div").css("display","block");
   if ($("#product_product_name").val().length == 0) {
       $('<li />').html("请填写产品名称").appendTo('#error-div');
       $('#name').addClass("error");
       $('#product_product_name').addClass("error");
          };
   if ($("#product_brief").val().length == 0) {
       $('<li />').html("请填写产品名称").appendTo('#error-div');
       $('#pro-brief').addClass("error");
       $('#product_brief').addClass("error");
       };
        };                
    });
  }
</script>

app/views/products/edit.html.erb
<% provide(:title, '产品编辑')  %>

<br>
<% if !notice.nil? %>
  <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= notice %> 
  </div>
<% end%>


<div class="panel panel-default">
<div class="panel-heading">修改产品信息</div>
  <!-- /.panel-heading -->
	<div class="panel-body">
			<div class="table-responsive">
			<%= render 'form' %>
			<%= link_to '查看', @product , class:"btn btn-outline btn-primary"%> 
			<%= link_to '返回', products_path , class:"btn btn-outline btn-primary"%>
			</div>
	</div>
</div>
<script type="text/javascript">
    form_send($(".edit_product").attr('action'), 'put');
</script>

app/views/products/index.html.erb
<% provide(:title, '产品管理')  %>
<br>
<% if !notice.nil? %>
  <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= notice %> 
  </div>
<% end%>

<div class="panel panel-default">
    <div class="panel-heading">产品管理</div>
      <!-- /.panel-heading --> 

      <div class="checkbox">
          <label><input type="checkbox"   id="allSelected">全选</label>
          <label><input type="checkbox"   id="inverSelected">反选</label>
      </div>
      <button type="button" class="btn btn-default delete" id="deleteIds">删除</button>
      <div class="search">
          <div class="search-in">
              <input class="form-control" type="text" id="search-in" value="<%=params[:search] %>">
          </div>
          <div class="search-p">
              <button type="button" class="btn btn-default delete" id="search">搜索</button>
          </div>
      </div>

          <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                      <thead>
                          <tr>
                            <td></td>
                            <td>产品名称</td>
                            <td>产品摘要</td>
                            <td>添加时间</td>
                            <td>修改时间</td>
                            <td>操作</td>

                        </tr>
                    </thead>
                        <% @products.each do |product| %>
                   <tbody>
                        <tr>
                        <td><input type="checkbox" id="chckBox" name="<%= product.id%>"></td>
                            <td>
                            <% if product.product_name.to_s.length >=10 %>
                                         <%= product.product_name.to_s[0,10]+'  ...' %>
                                  <% else %>
                                         <%= product.product_name %>
                                  <% end %>
                            </td>
                            <td>
                                  <% if product.brief.to_s.length >=10 %>
                                         <%= product.brief.to_s[0,10]+'  ...' %>
                                  <% else %>
                                         <%= product.brief%>
                                  <% end %>
                            </td>
                            <td><%= product.created_at.localtime.to_s(:db) %></td>
                            <td><%= product.updated_at.localtime.to_s(:db) %></td>
                            <td><a href="/products/<%=product.id%>">查看</a> 
                                <%= link_to '编辑', edit_product_path(product) %>
                                <%= link_to '删除', product, method: :delete, data: { confirm: '您确定要删除?' }%>
                            </td>
                        </tr>
                   </tbody>
                   <% end %>
                </table>
             
            <%= link_to '新建', new_product_path , class:"btn btn-outline btn-primary"%></li>
            </div>
            <!-- /.table-responsive -->
        <%= paginate @products, :outer_window => 3 %> 
      </div>
  </div>
</div>


<!-- <a data-method="delete" href="/products/85" rel="nofollow">删除</a> -->


<script type="text/javascript">
         $("#allSelected").change(function(event) {
           var checked = $(this).get(0).checked;
           $("#inverSelected").get(0).checked = false;
           $("input[id = chckBox]").each(function(index, checkBox) {
                    checkBox.checked = checked;
                  });
         });

         $("#inverSelected").change(function(event) {
           $("#allSelected").get(0).checked = false;
           $("input[id = chckBox]").each(function(index, checkBox) {
                    checkBox.checked = !checkBox.checked;
                  });
         });
 
         $("#deleteIds").click(function(event) {
           var ids = new String();
           $("input[id = chckBox]").each(function(index, checkBox) {
                    if (checkBox.checked) {
                      ids = ids + checkBox.name + ",";
                    };
                  });
          
           $.post('/products/destroy_ids', { ids: ids}, function(data) {
                  location.reload();
              
            }, "json");
         });

         $("#search").click(function(event) {
            location.href="?search="+$("#search-in").val();   
          });
        
</script>

app/views/products/new.html.erb
<% provide(:title, '添加产品')  %>
<br>
<div class="panel panel-default">
   <div class="panel-heading">新增产品</div>
      <div class="panel-body">
        <div class="table-responsive">
		<%= render 'form' %>
		<%= link_to '返回', products_path, class:"btn btn-outline btn-primary" %>
		</div>
	</div>
</div>

<script type="text/javascript">
     form_send($(".new_product").attr('action'), 'post');
</script>

app/views/products/show.html.erb
<% provide(:title, '产品展示')  %>
<br>
<% if !notice.nil? %>
  <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= notice %> 
  </div>
<% end%>
<div class="panel panel-default">
   <div class="panel-heading">产品信息</div>
      <div class="panel-body">
        <div class="table-responsive">
              <div class="time">
                <strong>添加时间:</strong>
                <%= @product.created_at.localtime.to_s(:db) %>
              </div>
              <div class="time">
                <strong>修改时间:</strong>
                <%= @product.updated_at.localtime.to_s(:db) %>
              </div>
              
              <div class="check_product">
                  <strong>产品名字:</strong>
                  <p><%= @product.product_name %></p>
              </div>
               <div class="check_product">
                  <strong>产品摘要:</strong>
                  <p><%= @product.brief %></p>
              </div>
              <div class="check_product" id="log" >
                <strong>产品描述:</strong>
              </div>
              <div class="button">
                      <%= link_to '编辑', edit_product_path(@product), class:"btn btn-outline btn-primary" %> 
                      <%= link_to '返回', products_path, class:"btn btn-outline btn-primary" %>
              </div>
        </div>
             <!-- /.table-responsive -->
    </div>
     <!-- /.panel-body -->
</div>
             <script type="text/javascript">
                a = $('<iframe/>', {id: 'foo',scrolling:'no',onload:'iFrameHeight(this)',name:'foo'});
                  a.appendTo('#log');
                  a.css('width', '98%');
                  a.css('border','0 none');
                 html = unescape("<%= @product.context %>");
                  $('#foo').contents().find('body').append(html);
                  function setIframeHeight(iframe) {
                    if (iframe) {
                      var iframeWin = iframe.contentWindow || iframe.contentDocument.parentWindow;
                      if (iframeWin.document.body) {
                        iframe.height = iframeWin.document.documentElement.scrollHeight || iframeWin.document.body.scrollHeight;
                      }
                    }
                  };
                  setIframeHeight(document.getElementById('foo'))
                </script>